ktor:
    application:
        modules:
            - zjt.projects.ApplicationKt.module
    deployment:
        port: 8080
    development: true
db:
    mongo:
        database:
            name: scrounge